import streamlit as st
import re
import requests
import base64
import io
from gtts import gTTS
from streamlit.components.v1 import html

def text_to_speech(text):
    if not text or text == "<p>Error generating content. Please try again.</p>":
        return None
    try:
        clean_text = re.sub(r'<[^>]+>', '', text).strip()
        clean_text = re.sub(r'[^a-zA-Z0-9.,?! ]', '', clean_text)
        clean_text = re.sub(r'-{2,}', '', clean_text)
        if not clean_text:
            return None
        tts = gTTS(text=clean_text, lang='en')
        audio_file = io.BytesIO()
        tts.write_to_fp(audio_file)
        audio_file.seek(0)
        audio_b64 = base64.b64encode(audio_file.read()).decode('utf-8')
        return audio_b64
    except Exception as e:
        st.error(f"Error generating audio: {str(e)}")
        return None

def copy_to_clipboard(text):
    clean_text = re.sub(r'<[^>]+>', '', text)
    html(f"""
    <button style="background-color: #4CAF50; color: white; padding: 0.6rem 1.2rem; border-radius: 10px; font-size: 1rem; font-weight: bold; cursor: pointer;" onclick="copyText()">Copy to Clipboard 📋</button>
    <script>
    function copyText() {{
        navigator.clipboard.writeText(`{clean_text}`).then(() => {{
            alert('Copied to clipboard!');
        }});
    }}
    </script>
    """)

def social_share_buttons(content, topic):
    clean_text = re.sub(r'<[^>]+>', '', content)[:280]
    encoded_text = requests.utils.quote(f"{clean_text} - Generated by Writeaidaily.com")
    twitter_url = f"https://twitter.com/intent/tweet?text={encoded_text}"
    linkedin_url = f"https://www.linkedin.com/sharing/share-offsite/?url=https://writeaidaily.com&title={requests.utils.quote(topic)}&summary={encoded_text}"
    col1, col2 = st.columns(2)
    with col1:
        st.markdown(f'<a href="{twitter_url}" target="_blank"><button style="background-color: #1DA1F2; color: white; padding: 0.5rem 1rem; border-radius: 10px; border: none;">Share on Twitter 🐦</button></a>', unsafe_allow_html=True)
    with col2:
        st.markdown(f'<a href="{linkedin_url}" target="_blank"><button style="background-color: #0077B5; color: white; padding: 0.5rem 1rem; border-radius: 10px; border: none;">Share on LinkedIn 💼</button></a>', unsafe_allow_html=True)